# -*- coding: utf-8 -*-
"""
PegaProx Pairing-Time Node Hardening

Deploys OS-layer security controls to a Proxmox node when it is added to
PegaProx management.  Steps (each independent — a failure warns, never aborts):

  1. ssh_key      — generate Ed25519 key pair; deploy public key to authorized_keys
  2. sudo_install — apt-get install sudo if not present
  3. sudoers      — deploy /etc/sudoers.d/pegaprox (LXC replication scope only)
  4. auditd_install — apt-get install auditd if not present
  5. audit_rules  — deploy /etc/audit/rules.d/pegaprox.rules and reload

Rolling Updates / SMBIOS / HA / Node Shell continue to use root SSH directly and
are NOT scoped by the sudoers policy deployed here.
"""

import io
import logging

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# File contents deployed to nodes
# ---------------------------------------------------------------------------

_SUDOERS_CONTENT = """\
# =============================================================
# PegaProx Scoped Sudoers Policy
# Generated by PegaProx pairing process
# Scope: LXC replication operations only
# Rolling Updates / SMBIOS / HA / Node Shell use root SSH directly
# =============================================================

Defaults:root    logfile=/var/log/pegaprox-sudo.log
Defaults:root    log_year
Defaults:root    log_host

root ALL=(ALL) NOPASSWD: /usr/bin/vzdump *
root ALL=(ALL) NOPASSWD: /usr/sbin/pct start *
root ALL=(ALL) NOPASSWD: /usr/sbin/pct stop *
root ALL=(ALL) NOPASSWD: /usr/sbin/pct status *
root ALL=(ALL) NOPASSWD: /usr/sbin/pct config *
root ALL=(ALL) NOPASSWD: /usr/sbin/qm start *
root ALL=(ALL) NOPASSWD: /usr/sbin/qm stop *
root ALL=(ALL) NOPASSWD: /usr/sbin/qm status *
root ALL=(ALL) NOPASSWD: /usr/sbin/qm config *
"""

_AUDIT_RULES_CONTENT = """\
# PegaProx Audit Rules - generated by PegaProx pairing process

# Watch sudoers file for modifications
-w /etc/sudoers.d/pegaprox -p wa -k pegaprox_sudoers

# Watch sudo audit log
-w /var/log/pegaprox-sudo.log -p wa -k pegaprox_sudo_log

# Track replication command invocations
-a always,exit -F arch=b64 -F exe=/usr/bin/vzdump -k pegaprox_backup
-a always,exit -F arch=b64 -F exe=/usr/sbin/pct -k pegaprox_lxc
-a always,exit -F arch=b64 -F exe=/usr/sbin/qm -k pegaprox_vm
"""

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _run(manager, node, cmd, timeout=90):
    """Run a shell command on a node via the manager's SSH pool. Returns stdout str or None."""
    return manager._ssh_node_output(node, cmd, timeout=timeout)


# ---------------------------------------------------------------------------
# Per-step functions — each returns (status, detail) or (status, detail, extra)
# ---------------------------------------------------------------------------

def _step_ssh_key(manager, node):
    """Generate an Ed25519 key pair and deploy the public key to authorized_keys.

    Returns (status, detail, private_pem_or_None).  If a key is already
    configured the step is skipped and None is returned as the key.
    """
    if getattr(manager.config, 'ssh_key', ''):
        return 'skip', 'SSH key already configured', None

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
        from cryptography.hazmat.primitives.serialization import (
            Encoding, NoEncryption, PrivateFormat, PublicFormat,
        )
    except ImportError:
        return 'warn', 'cryptography library not available — SSH key setup skipped', None

    try:
        priv = Ed25519PrivateKey.generate()
        private_pem = priv.private_bytes(
            Encoding.PEM, PrivateFormat.OpenSSH, NoEncryption()
        ).decode()
        pub_line = (
            priv.public_key().public_bytes(Encoding.OpenSSH, PublicFormat.OpenSSH).decode().strip()
            + " pegaprox-managed"
        )

        # Idempotent: append only if the exact line isn't already present.
        # Single-quoted heredoc prevents shell expansion of the key material.
        deploy_cmd = (
            "mkdir -p /root/.ssh && chmod 700 /root/.ssh && "
            f"grep -qxF '{pub_line}' /root/.ssh/authorized_keys 2>/dev/null || "
            f"echo '{pub_line}' >> /root/.ssh/authorized_keys && "
            "chmod 600 /root/.ssh/authorized_keys && echo OK"
        )
        out = _run(manager, node, deploy_cmd, timeout=30)
        if out is None or 'OK' not in out:
            return 'warn', 'Could not deploy SSH public key to authorized_keys (SSH failed)', None

        # Update in-memory config so all subsequent steps use key auth.
        manager.config.ssh_key = private_pem
        return 'ok', 'Ed25519 key generated and deployed to /root/.ssh/authorized_keys', private_pem

    except Exception as e:
        return 'warn', f'SSH key setup failed: {e}', None


def _step_install_sudo(manager, node):
    cmd = (
        "command -v sudo >/dev/null 2>&1 && echo PRESENT || "
        "DEBIAN_FRONTEND=noninteractive apt-get install -y sudo 2>&1 | tail -1 && echo INSTALLED"
    )
    out = _run(manager, node, cmd, timeout=120)
    if out is None:
        return 'warn', 'SSH failed'
    if 'PRESENT' in out:
        return 'skip', 'sudo already installed'
    if 'INSTALLED' in out:
        return 'ok', 'sudo installed via apt'
    return 'warn', f'Unexpected output: {out.strip()[:120]}'


def _step_deploy_sudoers(manager, node):
    # Write to a staging path first so we can validate with visudo -c before
    # moving into place.  Idempotent: skip if the file already exists and
    # passes validation (re-runs on reconfigure are safe).
    cmd = f"""\
if [ -f /etc/sudoers.d/pegaprox ] && visudo -c -f /etc/sudoers.d/pegaprox >/dev/null 2>&1; then
  echo ALREADY_VALID
else
  cat > /tmp/pp_sudoers_staging << 'SUDOEOF'
{_SUDOERS_CONTENT}
SUDOEOF
  if visudo -c -f /tmp/pp_sudoers_staging >/dev/null 2>&1; then
    cp /tmp/pp_sudoers_staging /etc/sudoers.d/pegaprox
    chmod 440 /etc/sudoers.d/pegaprox
    rm /tmp/pp_sudoers_staging
    echo DEPLOYED
  else
    rm -f /tmp/pp_sudoers_staging
    echo INVALID
  fi
fi"""
    out = _run(manager, node, cmd, timeout=30)
    if out is None:
        return 'warn', 'SSH failed'
    if 'ALREADY_VALID' in out:
        return 'skip', '/etc/sudoers.d/pegaprox already present and valid'
    if 'DEPLOYED' in out:
        return 'ok', '/etc/sudoers.d/pegaprox deployed (visudo validated, chmod 440)'
    if 'INVALID' in out:
        return 'warn', 'sudoers content failed visudo validation — file not deployed'
    return 'warn', f'Unexpected output: {out.strip()[:120]}'


def _step_install_auditd(manager, node):
    cmd = (
        "systemctl is-active auditd >/dev/null 2>&1 && echo ACTIVE || "
        "DEBIAN_FRONTEND=noninteractive apt-get install -y auditd >/dev/null 2>&1 && "
        "systemctl enable --now auditd >/dev/null 2>&1 && echo INSTALLED"
    )
    out = _run(manager, node, cmd, timeout=120)
    if out is None:
        return 'warn', 'SSH failed'
    if 'ACTIVE' in out:
        return 'skip', 'auditd already active'
    if 'INSTALLED' in out:
        return 'ok', 'auditd installed and started'
    return 'warn', f'Unexpected output: {out.strip()[:120]}'


def _step_deploy_audit_rules(manager, node):
    cmd = f"""\
if [ -f /etc/audit/rules.d/pegaprox.rules ]; then
  echo ALREADY_PRESENT
else
  mkdir -p /etc/audit/rules.d
  cat > /etc/audit/rules.d/pegaprox.rules << 'AUDITEOF'
{_AUDIT_RULES_CONTENT}
AUDITEOF
  augenrules --load >/dev/null 2>&1 || systemctl restart auditd >/dev/null 2>&1
  echo DEPLOYED
fi"""
    out = _run(manager, node, cmd, timeout=60)
    if out is None:
        return 'warn', 'SSH failed'
    if 'ALREADY_PRESENT' in out:
        return 'skip', '/etc/audit/rules.d/pegaprox.rules already present'
    if 'DEPLOYED' in out:
        return 'ok', '/etc/audit/rules.d/pegaprox.rules deployed and loaded'
    return 'warn', f'Unexpected output: {out.strip()[:120]}'


# ---------------------------------------------------------------------------
# Node-level orchestrator
# ---------------------------------------------------------------------------

def _harden_node(manager, node):
    """Run all hardening steps on one node.  Returns (steps, private_key_or_None)."""
    steps = []
    generated_key = None

    # SSH key step is special: it may produce a private key to persist.
    try:
        ssh_status, ssh_detail, generated_key = _step_ssh_key(manager, node)
    except Exception as e:
        ssh_status, ssh_detail, generated_key = 'error', str(e), None
    steps.append({'name': 'ssh_key', 'status': ssh_status, 'detail': ssh_detail})
    logger.info("[Hardening] %s/ssh_key: %s — %s", node, ssh_status, ssh_detail[:80])

    remaining_steps = [
        ('sudo_install',  _step_install_sudo),
        ('sudoers',       _step_deploy_sudoers),
        ('auditd_install', _step_install_auditd),
        ('audit_rules',   _step_deploy_audit_rules),
    ]
    for name, fn in remaining_steps:
        try:
            status, detail = fn(manager, node)
        except Exception as e:
            status, detail = 'error', str(e)
        steps.append({'name': name, 'status': status, 'detail': detail})
        logger.info("[Hardening] %s/%s: %s — %s", node, name, status, detail[:80])

    return steps, generated_key


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def deploy_pairing_hardening(manager):
    """Deploy pairing-time security hardening to every node in the cluster.

    Called from add_cluster() after the manager has connected and started.
    Never raises — all failures are captured in the returned result.

    Returns:
        {
            'success': bool,          # True if every step on every node is ok/skip
            'nodes': {
                node_name: {
                    'steps': [{'name', 'status', 'detail'}, ...]
                }
            },
            'ssh_key': str | None     # Private PEM if a key was generated; caller
                                      # should persist this to manager.config.ssh_key
                                      # and call save_config().
        }
    """
    result = {'success': True, 'nodes': {}, 'ssh_key': None}

    try:
        node_status = manager.get_node_status()
    except Exception as e:
        logger.warning("[Hardening] Could not enumerate nodes: %s — skipping hardening", e)
        result['success'] = False
        return result

    if not node_status:
        logger.warning("[Hardening] No nodes returned from get_node_status — skipping")
        result['success'] = False
        return result

    for node_name in node_status:
        logger.info("[Hardening] Starting hardening for node: %s", node_name)
        try:
            steps, node_key = _harden_node(manager, node_name)
        except Exception as e:
            steps = [{'name': 'all', 'status': 'error', 'detail': str(e)}]
            node_key = None
            logger.error("[Hardening] Uncaught error on %s: %s", node_name, e)

        result['nodes'][node_name] = {'steps': steps}

        # Capture the first generated key (all nodes share the same key pair).
        if node_key and result['ssh_key'] is None:
            result['ssh_key'] = node_key

        # Any error/warn on any step means overall success = False.
        if any(s['status'] in ('error', 'warn') for s in steps):
            result['success'] = False

    return result
